###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts?owner=POP


###
  
POST  http://localhost:3000/posts
Content-Type: application/json

{
"title": "Hello World",
"content": "This is my first post!",
"owner": "POP"
} 


###

DELETE  http://localhost:3000/posts


###

DELETE  http://localhost:3000/posts/124124123